### PR TITLE
Fixes #284

### LINKED ISSUE #284: Sidenav now extends to meet the md-content height
The add idea button is basically not visible because of this. I have no idea which commit caused this. I noticed it fairly irregularly, but now I think it's if you login on the home page.

### PR DESCRIPTION
**Pull request by Mctalian**
@alanlgirard, @bcbrennecke, @YashdalfTheGray, @davethenipper, @monotkate 

Reviewers
- [x] First
- [x] Second

### CODE REVIEW

**Comment by alanlgirard** [comment]
Approved

**Comment by Mctalian** [comment]
#284 just to reference back.

**Comment by Mctalian** [comment]
Super confused that this doesn't show up in production, but shows up locally... but this should fix it either way.

**Comment by davethenipper** [comment]
Approved

**Pull request merged**
