### PR TITLE
Navigating to a non-existent idea behaves appropriately.

### PR DESCRIPTION
**Pull request by Mctalian**
This used to work, but the back-end changes broke this.

When navigating to an idea that doesn't exist (someone deleted it and you're following a link to the deleted idea), it was supposed to reroute you back to the home state and toast you with "Sorry, that idea doesn't exist" or something to that effect.

What it was doing was just displaying a blank idea page. Now it's fixed.

Reviewers: 
- [x] @bcbrennecke (or other)
- [x] @alanlgirard (or other)

### CODE REVIEW

**Comment by bcbrennecke** [comment]
Convenient!

**Comment by YashdalfTheGray** [comment]
I have fixed this in the past. Something else broke this. Specifically
remember fixing deleting ideas after @Mctalian pointed it out.

Yash Kulshrestha
yash.kulshrestha@gmail.com
(614)563-1163

**Comment by Mctalian** [comment]
That was slightly different. That was SSE related, this is just a bogus ID.

We now return 404 and IDEA_NOT_FOUND instead of 200, so the logic needed to
be moved to the error handler since it's not a 2xx HTTP status.

**Comment by YashdalfTheGray** [comment]
Approved.

**Comment by alanlgirard** [comment]
Approved

**Pull request merged**
