### PR TITLE
Disable events

### LINKED ISSUE #277: Hide Events
For now it looks like we do not want user's to tag events themselves.  Holly is on board with the idea of allowing engineers to work on things outside of Logix.

### PR DESCRIPTION
**Pull request by Mctalian**
This is kinda temporary since there's a bug and we need to discuss how events are going to be utilized in the future.

Closes #277 

@YashdalfTheGray, @davethenipper, @alanlgirard 

Reviewers
- [x] First
- [x] Second

### CODE REVIEW

**Comment by alanlgirard** [comment]
Approved.  We should log an issue to revisit the events so we don't forget about it.

**Comment by bcbrennecke** [comment]
Approve.

**Comment by Mctalian** [comment]
@alanlgirard #288 Created

**Comment by LongArmMcGee** [comment]
My opinion on the matter: events are a useful tool to organize ideas according to real world activities. If a specific group doesn't want to use them that's fine. That doesn't mean someone else won't.

**Comment by Mctalian** [comment]
Please see the new issue with discussion around events. Right now there is
a bug with events due to a change that was pushed so this is a temporary
disabling until we get a better idea of how to handle events. It's probably
like #288 or #289 or something.

**Pull request merged**
