### PR TITLE
01 Idea Cards

### PR DESCRIPTION
**Pull request by YashdalfTheGray**
Changes
* (cleanup) removed the sidenav that was hanging around for no reason
* (cleanup) removed `ideaItem`
* (refactor) moved `topIdeas` into the ideas folder
* (feature) added a larger description to one idea so I could test
* (feature) added `getAbstract()` with support for variable length abstracts
* (feature) added the `ideaCard` directive with image support
* (feature) switched `topIdeas` to use `ideaCard`
* (feature) added `ideaCard` to the build
* (fix) `gulp code-check` errors

### CODE REVIEW

**Comment by davethenipper** [comment]
PO approved, pending I remember what the "hero image" is.

**Comment by YashdalfTheGray** [comment]
IE issues we can pick up as part of the unjankify card. The hero image is the image that goes with the idea.  In Material Design it's called a hero image. 

Also, I'm not going to merge this code, someone else is going to have to do it.

**Comment by davethenipper** [comment]
@alanlgirard Can we make you Card Czar? Pending your approval, you would merge this in.

**Comment by alanlgirard** [comment]
Approved.  IE Issues will be covered under unjankify card

**Pull request merged**
