### PR TITLE
Carousel Additions

### PR DESCRIPTION
**Pull request by davethenipper**
Added 3 images to the carousel:
1) Our Logo
2) A quick and easy "subscribe" picture
3) A future feature tab

The new images can be seen in the changes.  I'm not married to any of them, but figured it is at least a start.  Probably "good enough" for a re-launch?

Approvers: @YashdalfTheGray @alanlgirard @bcbrennecke

### CODE REVIEW

**Comment by davethenipper** [comment]
Not much to test here.  Images all appear in the carousel both in chrome & IE.  Only thing I notice is that image 3 appear first.  I can rename files and make our logo appear first if anyone cares?

**Comment by bcbrennecke** [comment]
The red 'subscribe' gives me flashbacks or currentbacks to SAP and the terrible time entry banner that is red.... can we give it a different color?

**Comment by davethenipper** [comment]
Sure.  Pick one!

**Comment by bcbrennecke** [comment]
How about #03A9F4 ? 
[https://material.google.com/style/color.html#color-color-palette](url)

**Comment by bcbrennecke** [comment]
I'm softening on the 'Innovative Colors' front

**Comment by davethenipper** [comment]
I like that blue.  unless there's objections, I'll change it.

**Comment by davethenipper** [comment]
Did not realize the email changes would be pulled into this after I merged them to my master (duh).  

I blame you guys for not looking at my code fast enough XD

**Comment by alanlgirard** [comment]
The images look good enough for now but the Innovate logo image will need some padding around the logo so it's not right up against the edges.  

Good work on getting nodemailer working but should have been another PR.  This will enable you to do the subscription card a lot easier.

**Approved** even though you suck at jshint and jscs!

**Comment by bcbrennecke** [comment]
Instead of a stub, can we have it actually send an email every time the server starts up to the Innovate mailbox that says 'The server restarted'.  This could be useful

**Comment by davethenipper** [comment]
I like that a lot. Other's thoughts?

**Comment by davethenipper** [comment]
After talking with Yash:
We'll leave node mailer in for now.  We need to do some research into what SharePoint can and can't do with notifications.  This will probably happen in 2.0

My next story will be:
1) Let users subscribe/unsubscribe to the mailing list will be another.
This should be enough to allow us to pull a list of emails for events/news.

After SharePoint tech spike:
2) So creating a working email service and tests will be one.

**Pull request merged**
