### PR TITLE
Future Feature Page

### PR DESCRIPTION
**Pull request by davethenipper**
Added a Future Feature page.  More of a placeholder than anything.  

I'll be adding email the team links in this page and the about page.  The group email will put all developers emails into a single outlook email.

I'll be removing the individual email links in the about page.

Approvals: First two people

### CODE REVIEW

**Comment by YashdalfTheGray** [comment]
Little nitpicky but this branch should be on your fork and then you should push to master on your fork and then create a PR.

**Comment by davethenipper** [comment]
I'll remember that for next time.  And next time should be in a few hours!

**Comment by alanlgirard** [comment]
Everything checks out for a basic place holder.

Improvements
- Look into getting a single email setup for the group. 
- With the growing amount of links at the bottom of the home page, display links in a row with dividers or implement some type of footer for the webpage.

**Comment by Mctalian** [comment]
Future:

If we don't set up a single email, we can probably find a way to reuse some of @LongArmMcGee's work with team emails since the developers are stored as objects in an array in the controller.

A single email would trump this.

**Comment by davethenipper** [comment]
Awesome, I'll take those as approvals and toss up the next one.

**Pull request closed without merging**
